package com.example.adm.minhalanchonetedelicia;

/**
 * Created by adm on 04/12/2017.
 */

public enum Categoria {
    SUCOONDATROPICAL,VITAMINAPLANETARIA,HAMBURGUEREXAGERADO,PASTELSUPER,EMPADAOLHOGRANDE,BOLIVIADOQUENTE,QUIBEPOP,ESFIRRADOSABOR,CREPIOCASABOROSA,PAODENUVEM,BRUSCHETTAINTEGRAL
}
